quarkus.http.port=8702

mp.openapi.extensions.smallrye.info.title=Book API
mp.openapi.extensions.smallrye.info.version=1.0
mp.openapi.extensions.smallrye.info.description=Creates books
mp.openapi.extensions.smallrye.info.name=@agoncal
mp.openapi.extensions.smallrye.info.url=https://twitter.com/agoncal