%prod.books.genre=Information Technology
%dev.books.genre=drama
%test.books.genre=IT
%staging.books.genre=Custom profile

quarkus.log.category."io.quarkus".level=INFO
%dev.quarkus.log.category."io.quarkus".level=INFO
quarkus.log.category."org.agoncal".level=INFO
quarkus.banner.enabled=true